export const GENERAL_CLOSE_ERROR_DIALOG = 'GENERAL_CLOSE_ERROR_DIALOG';
export const GENERAL_REFRESH = 'GENERAL_REFRESH';
export const GENERAL_START_LOADING = 'GENERAL_START_LOADING';
export const GENERAL_FINISH_LOADING = 'GENERAL_FINISH_LOADING';
export const GENERAL_SHOW_ERROR = 'GENERAL_SHOW_ERROR';

export const TODOS_ADD = 'TODOS_ADD';
export const TODOS_FORM_ERROR = 'TODOS_FORM_ERROR';
export const TODOS_LOAD = 'TODOS_LOAD';
